import { pgTable, text, serial, integer, boolean, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { relations } from "drizzle-orm";
import { z } from "zod";

// =========================================================
// 1. AUTHENTICATION TABLES
// =========================================================
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(), // Will store hashed password
  name: text("name").notNull(),
  email: text("email").notNull().unique(), // Unique is critical for login
  isAdmin: boolean("is_admin").default(false).notNull(), // Handles Admin redirection
});

// =========================================================
// 2. RESERVATIONS TABLE
// =========================================================
export const reservations = pgTable("reservations", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  date: text("date").notNull(), // Storing as YYYY-MM-DD string
  time: text("time").notNull(),
  guests: integer("guests").notNull(),
  status: text("status").default("confirmed").notNull(),
  qrUrl: text("qr_url"), // URL to the QR code image in S3
  createdAt: timestamp("created_at").defaultNow(),
});

// =========================================================
// 3. MENU MANAGEMENT TABLES
// =========================================================
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(), // e.g., 'breakfast', 'mains'
});

export const menuItems = pgTable("menu_items", {
  id: serial("id").primaryKey(),
  categoryId: integer("category_id").notNull(), // Foreign Key to categories
  name: text("name").notNull(),
  description: text("description"),
  price: integer("price").notNull(), // Stored in cents (e.g., 1000 = $10.00)
  imageUrl: text("image_url"),
  available: boolean("available").default(true).notNull(),
});

// =========================================================
// 4. RELATIONS (For "Join" queries)
// =========================================================

// A Category has many Menu Items
export const categoryRelations = relations(categories, ({ many }) => ({
  items: many(menuItems),
}));

// A Menu Item belongs to one Category
export const menuItemRelations = relations(menuItems, ({ one }) => ({
  category: one(categories, {
    fields: [menuItems.categoryId],
    references: [categories.id],
  }),
}));

// =========================================================
// 5. ZOD SCHEMAS (For Form Validation)
// =========================================================

// User Registration Schema
export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  isAdmin: true // Users cannot make themselves admin
});

// Reservation Form Schema
export const insertReservationSchema = createInsertSchema(reservations).omit({
  id: true,
  status: true,
  createdAt: true,
  qrUrl: true // Generated by backend, not user input
});

// Menu Item Schema
export const insertMenuItemSchema = createInsertSchema(menuItems).omit({
  id: true
});

export const insertCategorySchema = createInsertSchema(categories).omit({
  id: true
});

// =========================================================
// 6. TYPES (For TypeScript)
// =========================================================
export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

export type Reservation = typeof reservations.$inferSelect;
export type InsertReservation = typeof reservations.$inferInsert;

export type Category = typeof categories.$inferSelect;
export type MenuItem = typeof menuItems.$inferSelect;